[package]
name = "rustypacket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
lazy_static = "1.4.0"
hex = "0.4.3"
pretty_assertions = "1.4.0"
